### ISSUE TITLE
SemanticLogger is not working

### ISSUE THREAD

**Issue by rade-tomovic** [Vonage/vonage-ruby-sdk#320]
I want to be able to use any logger. Currently, SemanticLogger is not working for no obvious reason. 

```
     TypeError:
       Parameter 'logger': Expected type T.nilable(T.any(ActiveSupport::BroadcastLogger, Logger, Vonage::Logger)), got type SemanticLogger::Logger with hash 2142317253973070942
       Caller: /home/rade/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/vonage-7.28.0/lib/vonage/config.rb:15
       Definition: /home/rade/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/vonage-7.28.0/lib/vonage/config.rb:139 (Vonage::Config#logger=)
```

Config:

```ruby
def client
      @client ||= Vonage::Client.new(
        api_key: ENV["VONAGE_API_KEY"],
        api_secret: ENV["VONAGE_API_SECRET"],
        logger: nil,
      ).sms
    end
```
